language: node_js
node_js:
  - "stable"
before_install:
  - npm install typescript && npm run install:all
  - npm run build
after_script:
  - npm install coveralls
  - coveralls < coverage/lcov.info
before_deploy:
  - npm run build
deploy:
  provider: npm
  email: matthias.giger@namics.com
  api_key: $NPM_TOKEN
  on:
    tags: true
